---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: dromedary-development

test:
  <<: *default
  database: dromedary-test

production:
  <<: *default
  database: dromedary
