blacklight:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/dromedary-development" %>

solr:
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/dromedary-development" %>

secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "somesecretkey" %>



db:
  url: unused

cable:
  adapter: async
  url: unused
  channel_prefix: dromedary


relative_url_root: /

data_dir: ./data
build_dir: ./data/build

log_dir: ./log

#data_dir: /home/esty/github/mlibrary/med/data
#build_dir: /home/esty/github/mlibrary/med/data/build
