---
name: "Build branch image"

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - webapp
          - assets
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{secrets.GH_PACKAGE_READ_TOKEN}}
        with:
          context: .
          file: Dockerfile.prod
          target: ${{ matrix.target }}
          push: true
          tags: |
            ghcr.io/mlibrary/dromedary/dromedary_branch_${{ matrix.target }}:latest
            ghcr.io/mlibrary/dromedary/dromedary_branch_${{ matrix.target }}:${{ github.ref_name }}
